//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.12 at 06:37:34 PM SGT 
//


package com.sysgrate.client.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sysgrate.client.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sysgrate.client.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCampaigns }
     * 
     */
    public GetCampaigns createGetCampaigns() {
        return new GetCampaigns();
    }

    /**
     * Create an instance of {@link GetCampaignsResponse }
     * 
     */
    public GetCampaignsResponse createGetCampaignsResponse() {
        return new GetCampaignsResponse();
    }

    /**
     * Create an instance of {@link OWCampaigns }
     * 
     */
    public OWCampaigns createOWCampaigns() {
        return new OWCampaigns();
    }

    /**
     * Create an instance of {@link AppendContactsToCampaign }
     * 
     */
    public AppendContactsToCampaign createAppendContactsToCampaign() {
        return new AppendContactsToCampaign();
    }

    /**
     * Create an instance of {@link OWContact }
     * 
     */
    public OWContact createOWContact() {
        return new OWContact();
    }

    /**
     * Create an instance of {@link AppendContactsToCampaignResponse }
     * 
     */
    public AppendContactsToCampaignResponse createAppendContactsToCampaignResponse() {
        return new AppendContactsToCampaignResponse();
    }

    /**
     * Create an instance of {@link Get200CampaignContacts }
     * 
     */
    public Get200CampaignContacts createGet200CampaignContacts() {
        return new Get200CampaignContacts();
    }

    /**
     * Create an instance of {@link Get200CampaignContactsResponse }
     * 
     */
    public Get200CampaignContactsResponse createGet200CampaignContactsResponse() {
        return new Get200CampaignContactsResponse();
    }

    /**
     * Create an instance of {@link OWContacts }
     * 
     */
    public OWContacts createOWContacts() {
        return new OWContacts();
    }

    /**
     * Create an instance of {@link OutboundLogin }
     * 
     */
    public OutboundLogin createOutboundLogin() {
        return new OutboundLogin();
    }

    /**
     * Create an instance of {@link OutboundLoginResponse }
     * 
     */
    public OutboundLoginResponse createOutboundLoginResponse() {
        return new OutboundLoginResponse();
    }

    /**
     * Create an instance of {@link OutboundLogoff }
     * 
     */
    public OutboundLogoff createOutboundLogoff() {
        return new OutboundLogoff();
    }

    /**
     * Create an instance of {@link OutboundLogoffResponse }
     * 
     */
    public OutboundLogoffResponse createOutboundLogoffResponse() {
        return new OutboundLogoffResponse();
    }

    /**
     * Create an instance of {@link ArrayOfOWCampaign }
     * 
     */
    public ArrayOfOWCampaign createArrayOfOWCampaign() {
        return new ArrayOfOWCampaign();
    }

    /**
     * Create an instance of {@link OWCampaign }
     * 
     */
    public OWCampaign createOWCampaign() {
        return new OWCampaign();
    }

    /**
     * Create an instance of {@link OWSkillset }
     * 
     */
    public OWSkillset createOWSkillset() {
        return new OWSkillset();
    }

    /**
     * Create an instance of {@link OWStatus }
     * 
     */
    public OWStatus createOWStatus() {
        return new OWStatus();
    }

    /**
     * Create an instance of {@link ArrayOfOWDispositioncode }
     * 
     */
    public ArrayOfOWDispositioncode createArrayOfOWDispositioncode() {
        return new ArrayOfOWDispositioncode();
    }

    /**
     * Create an instance of {@link OWDispositioncode }
     * 
     */
    public OWDispositioncode createOWDispositioncode() {
        return new OWDispositioncode();
    }

    /**
     * Create an instance of {@link OWAddress }
     * 
     */
    public OWAddress createOWAddress() {
        return new OWAddress();
    }

    /**
     * Create an instance of {@link ArrayOfOWCustomField }
     * 
     */
    public ArrayOfOWCustomField createArrayOfOWCustomField() {
        return new ArrayOfOWCustomField();
    }

    /**
     * Create an instance of {@link OWCustomField }
     * 
     */
    public OWCustomField createOWCustomField() {
        return new OWCustomField();
    }

    /**
     * Create an instance of {@link OWPhoneNumber }
     * 
     */
    public OWPhoneNumber createOWPhoneNumber() {
        return new OWPhoneNumber();
    }

    /**
     * Create an instance of {@link ArrayOfOWContact }
     * 
     */
    public ArrayOfOWContact createArrayOfOWContact() {
        return new ArrayOfOWContact();
    }

}
