//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.12 at 06:37:34 PM SGT 
//


package com.sysgrate.client.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for OWCampaign complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OWCampaign"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfContacts" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="NumberOfContactsProcessed" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="DateCreated" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="Owner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StartDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="Skillset" type="{http://datatypes.outboundwebservices.ccmm.applications.nortel.com}OWSkillset" minOccurs="0"/&gt;
 *         &lt;element name="Status" type="{http://datatypes.outboundwebservices.ccmm.applications.nortel.com}OWStatus" minOccurs="0"/&gt;
 *         &lt;element name="StartOfRun" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Priority" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="LoadContactsPerInterval" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="DialingPrefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AutoDialTimeOut" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="MinimumRingTime" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="Locked" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="DispositionCodes" type="{http://datatypes.outboundwebservices.ccmm.applications.nortel.com}ArrayOfOWDispositioncode" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfContactsClosed" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OWCampaign", propOrder = {
    "id",
    "name",
    "description",
    "numberOfContacts",
    "numberOfContactsProcessed",
    "dateCreated",
    "owner",
    "startDateTime",
    "skillset",
    "status",
    "startOfRun",
    "priority",
    "loadContactsPerInterval",
    "dialingPrefix",
    "autoDialTimeOut",
    "minimumRingTime",
    "locked",
    "dispositionCodes",
    "numberOfContactsClosed"
})
public class OWCampaign {

    @XmlElement(name = "ID")
    protected long id;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "NumberOfContacts")
    protected long numberOfContacts;
    @XmlElement(name = "NumberOfContactsProcessed")
    protected long numberOfContactsProcessed;
    @XmlElement(name = "DateCreated", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateCreated;
    @XmlElement(name = "Owner")
    protected String owner;
    @XmlElement(name = "StartDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDateTime;
    @XmlElement(name = "Skillset")
    protected OWSkillset skillset;
    @XmlElement(name = "Status")
    protected OWStatus status;
    @XmlElement(name = "StartOfRun")
    protected boolean startOfRun;
    @XmlElement(name = "Priority")
    protected long priority;
    @XmlElement(name = "LoadContactsPerInterval")
    protected long loadContactsPerInterval;
    @XmlElement(name = "DialingPrefix")
    protected String dialingPrefix;
    @XmlElement(name = "AutoDialTimeOut")
    protected long autoDialTimeOut;
    @XmlElement(name = "MinimumRingTime")
    protected long minimumRingTime;
    @XmlElement(name = "Locked")
    protected boolean locked;
    @XmlElement(name = "DispositionCodes")
    protected ArrayOfOWDispositioncode dispositionCodes;
    @XmlElement(name = "NumberOfContactsClosed")
    protected long numberOfContactsClosed;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the numberOfContacts property.
     * 
     */
    public long getNumberOfContacts() {
        return numberOfContacts;
    }

    /**
     * Sets the value of the numberOfContacts property.
     * 
     */
    public void setNumberOfContacts(long value) {
        this.numberOfContacts = value;
    }

    /**
     * Gets the value of the numberOfContactsProcessed property.
     * 
     */
    public long getNumberOfContactsProcessed() {
        return numberOfContactsProcessed;
    }

    /**
     * Sets the value of the numberOfContactsProcessed property.
     * 
     */
    public void setNumberOfContactsProcessed(long value) {
        this.numberOfContactsProcessed = value;
    }

    /**
     * Gets the value of the dateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateCreated() {
        return dateCreated;
    }

    /**
     * Sets the value of the dateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateCreated(XMLGregorianCalendar value) {
        this.dateCreated = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the startDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDateTime() {
        return startDateTime;
    }

    /**
     * Sets the value of the startDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDateTime(XMLGregorianCalendar value) {
        this.startDateTime = value;
    }

    /**
     * Gets the value of the skillset property.
     * 
     * @return
     *     possible object is
     *     {@link OWSkillset }
     *     
     */
    public OWSkillset getSkillset() {
        return skillset;
    }

    /**
     * Sets the value of the skillset property.
     * 
     * @param value
     *     allowed object is
     *     {@link OWSkillset }
     *     
     */
    public void setSkillset(OWSkillset value) {
        this.skillset = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link OWStatus }
     *     
     */
    public OWStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link OWStatus }
     *     
     */
    public void setStatus(OWStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the startOfRun property.
     * 
     */
    public boolean isStartOfRun() {
        return startOfRun;
    }

    /**
     * Sets the value of the startOfRun property.
     * 
     */
    public void setStartOfRun(boolean value) {
        this.startOfRun = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public long getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(long value) {
        this.priority = value;
    }

    /**
     * Gets the value of the loadContactsPerInterval property.
     * 
     */
    public long getLoadContactsPerInterval() {
        return loadContactsPerInterval;
    }

    /**
     * Sets the value of the loadContactsPerInterval property.
     * 
     */
    public void setLoadContactsPerInterval(long value) {
        this.loadContactsPerInterval = value;
    }

    /**
     * Gets the value of the dialingPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDialingPrefix() {
        return dialingPrefix;
    }

    /**
     * Sets the value of the dialingPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDialingPrefix(String value) {
        this.dialingPrefix = value;
    }

    /**
     * Gets the value of the autoDialTimeOut property.
     * 
     */
    public long getAutoDialTimeOut() {
        return autoDialTimeOut;
    }

    /**
     * Sets the value of the autoDialTimeOut property.
     * 
     */
    public void setAutoDialTimeOut(long value) {
        this.autoDialTimeOut = value;
    }

    /**
     * Gets the value of the minimumRingTime property.
     * 
     */
    public long getMinimumRingTime() {
        return minimumRingTime;
    }

    /**
     * Sets the value of the minimumRingTime property.
     * 
     */
    public void setMinimumRingTime(long value) {
        this.minimumRingTime = value;
    }

    /**
     * Gets the value of the locked property.
     * 
     */
    public boolean isLocked() {
        return locked;
    }

    /**
     * Sets the value of the locked property.
     * 
     */
    public void setLocked(boolean value) {
        this.locked = value;
    }

    /**
     * Gets the value of the dispositionCodes property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfOWDispositioncode }
     *     
     */
    public ArrayOfOWDispositioncode getDispositionCodes() {
        return dispositionCodes;
    }

    /**
     * Sets the value of the dispositionCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfOWDispositioncode }
     *     
     */
    public void setDispositionCodes(ArrayOfOWDispositioncode value) {
        this.dispositionCodes = value;
    }

    /**
     * Gets the value of the numberOfContactsClosed property.
     * 
     */
    public long getNumberOfContactsClosed() {
        return numberOfContactsClosed;
    }

    /**
     * Sets the value of the numberOfContactsClosed property.
     * 
     */
    public void setNumberOfContactsClosed(long value) {
        this.numberOfContactsClosed = value;
    }

}
