//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.12 at 06:37:34 PM SGT 
//


package com.sysgrate.client.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OWDispositioncode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OWDispositioncode"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RetryTimeOut" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="NumbericValue" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="MaxRetryCount" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="Deletable" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="CallRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="MarkAsDeleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="SaveAgentScript" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OWDispositioncode", propOrder = {
    "id",
    "name",
    "retryTimeOut",
    "numbericValue",
    "maxRetryCount",
    "deletable",
    "callRequired",
    "markAsDeleted",
    "saveAgentScript"
})
public class OWDispositioncode {

    @XmlElement(name = "Id")
    protected long id;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "RetryTimeOut")
    protected long retryTimeOut;
    @XmlElement(name = "NumbericValue")
    protected long numbericValue;
    @XmlElement(name = "MaxRetryCount")
    protected long maxRetryCount;
    @XmlElement(name = "Deletable")
    protected boolean deletable;
    @XmlElement(name = "CallRequired")
    protected boolean callRequired;
    @XmlElement(name = "MarkAsDeleted")
    protected boolean markAsDeleted;
    @XmlElement(name = "SaveAgentScript")
    protected boolean saveAgentScript;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the retryTimeOut property.
     * 
     */
    public long getRetryTimeOut() {
        return retryTimeOut;
    }

    /**
     * Sets the value of the retryTimeOut property.
     * 
     */
    public void setRetryTimeOut(long value) {
        this.retryTimeOut = value;
    }

    /**
     * Gets the value of the numbericValue property.
     * 
     */
    public long getNumbericValue() {
        return numbericValue;
    }

    /**
     * Sets the value of the numbericValue property.
     * 
     */
    public void setNumbericValue(long value) {
        this.numbericValue = value;
    }

    /**
     * Gets the value of the maxRetryCount property.
     * 
     */
    public long getMaxRetryCount() {
        return maxRetryCount;
    }

    /**
     * Sets the value of the maxRetryCount property.
     * 
     */
    public void setMaxRetryCount(long value) {
        this.maxRetryCount = value;
    }

    /**
     * Gets the value of the deletable property.
     * 
     */
    public boolean isDeletable() {
        return deletable;
    }

    /**
     * Sets the value of the deletable property.
     * 
     */
    public void setDeletable(boolean value) {
        this.deletable = value;
    }

    /**
     * Gets the value of the callRequired property.
     * 
     */
    public boolean isCallRequired() {
        return callRequired;
    }

    /**
     * Sets the value of the callRequired property.
     * 
     */
    public void setCallRequired(boolean value) {
        this.callRequired = value;
    }

    /**
     * Gets the value of the markAsDeleted property.
     * 
     */
    public boolean isMarkAsDeleted() {
        return markAsDeleted;
    }

    /**
     * Sets the value of the markAsDeleted property.
     * 
     */
    public void setMarkAsDeleted(boolean value) {
        this.markAsDeleted = value;
    }

    /**
     * Gets the value of the saveAgentScript property.
     * 
     */
    public boolean isSaveAgentScript() {
        return saveAgentScript;
    }

    /**
     * Sets the value of the saveAgentScript property.
     * 
     */
    public void setSaveAgentScript(boolean value) {
        this.saveAgentScript = value;
    }

}
